---
abstract: 'Perl interface to Livedoor Weather Web Service'
author:
  - 'Masahiro Nagano <kazeburo@nomadscafe.jp>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Livedoor-Weather
no_index:
  directory:
    - t
    - inc
requires:
  JSON: 0
  URI::Fetch: 0
  XML::Simple: 0
version: 0.03
