# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-Livedoor-Weather
version:      0.02
version_from: lib/WebService/Livedoor/Weather.pm
installdirs:  site
requires:
    URI::Fetch:                    0
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
